### ISSUE TITLE
since ember-template-compiler.js

### ISSUE THREAD

**Issue by haldiggs** [kingpin2k/HandlebarsHelper#7]
I have been using this package for my Ember for a while. I wondered since the latest ember versions (1.11.*) are replacing handlebars.js with ember-template-compiler.js is this package still viable? will it still handle the hbs files in my mvc projects?

**Comment by haldiggs** [comment]
ok we are now using the kludge way of compiling Ember using he latest Ember-Cli, and then having the MVC application call the proper scripts as needed depending on the Ember application location. Kinda sucks... but it works. So I'm guessing being able to just write .esg files and link to handler -bars templates like I did with this project in the past are done?

**Comment by kingpin2k** [comment]
Since ember switched to htmlbars a split project was formed supporting the htmlbars compiler (which is the ember-template-compiler). It looks like you found it, but for people who find this question.  https://github.com/kingpin2k/HTMLBarsHelper
